
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 941813
	#The name of the modpack
	modpackName = "Scary spiced HQGN"
	#The version of the modpack
	modpackVersion = "1.0.1b"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false
